= {lab_name}

Welcome to the Red Hat OpenStack Services on OpenShift (RHOSO) lab instructions.
These instructions will guide you through the installation of the next generation of Red Hat's OpenStack product onto an existing OpenShift Cluster utilizing a bastion host and a single host for the data plane.

You have four installation options: 

* xref:connected.adoc[Install RHOSO using CDN - Connected environment]
* xref:disconnected.adoc[Install RHOSO using Satellite and Quay - Disconnected Environment]
* xref:updates.adoc[Install a previous version of RHOSO to update it to the latest]
* xref:gitops.adoc[Install and discover RHOSO using Gitops ArgoCD - LAB IN MAINTENANCE]
* xref:breakfix.adoc[Install and discover RHOSO using Gitops ArgoCD. Break & Fix - LAB IN MAINTENANCE]

Then if you want to go through a Vmware to RHOSO migration:
* xref:migration.adoc[Vmware to RHOSO VM migration using os-migrate vmware migration kit] 

Within the lab environment, you will be able to copy and paste the specified commands into the CLI.
For some steps you may also need to edit some of the commands from the  instructions.

*Be sure to review all commands carefully both for functionality and syntax!*
