# Validation du cloud déployé

## Installer l'opérateur de test

Installez l'opérateur de test dans le projet openstack-operators.

Assurez-vous que vous êtes dans le projet OpenStack :

[source,bash,role=execute]
----
oc project openstack
----

Préparez le secret pour l'installation des opérateurs de test :

Connectez-vous avec votre compte Red Hat et créez un secret :

[source,bash,role=execute]
----
podman login --username "6340056|osp-on-ocp-lb1374" --password "eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiI1Y2EzM2NjNGY4NWM0MmZmYTI3YmU5Y2UyMWI3M2JjMCJ9.GAxgg6Ht2oCS8zxHdwQw9kSD6RHeQOWYaDOcnQB5RElewQKvZmcNWi-YJdInJ5iXTE9r9tGVIN7fhFJL7f-hhL1PK2RVzZHD8qyfkMWcCEF5GUvp8rDX4GDrSkqjpUD44teWYkOy9Nb-3pOGzRIC7qs88uSxMz7hfil4I_HmjF4AAPIi4j3QZhp0lqrXzzf7vt6NLlizDFa2XTcPf_vQqReFu3A_5iWfy8XmLlC7QIixeVv2IE-ahRqM_UDCf5Dg3n2WpYvmP5jcSPFOLoT7sMimyeaPBna793boiX2swmeGHQ23tx1nFavCUavGv_cDRAvzVXCJ2NROTJ5unHiN7CXEbzm4Rg-65tY4D0YynTU8L6t0gYtXYYY9_wi1xNs-cShAmCMh1ySJn9nBcq4ydvH7eQnhSEvoK0bPsN_vWJCgOQBQyOdpTfRMU6piAy9H1zJ0KzsSzuKSS8fX0m9oN7narZPl34DTiEUTDeW8_SS6vJjHr_Q9O_X4mVeeQhH2ocN_4M9R6A89tmQ2jObuWm-cu1Yk-G6FSPUONhsoC_99nQnICS4mAuCWWDHxFY61hIrreVZBSH053MgfSaG2sqTb26MkxKWx-TP1sx18pb1xmo4IQEwILIbLlSPA3vafbrbQO5RQcm3UYKtYwev0vAlL5taXiTuLEyPscdzv0Sc" registry.redhat.io --authfile auth.json
----

Créer un secret pour le registre :

[source,bash,role=execute]
----
oc create secret generic osp-operators-secret \
 -n openstack-operators \
 --from-file=.dockerconfigjson=auth.json \
 --type=kubernetes.io/dockerconfigjson
----


Créez une source de catalogue (catalogsource), un groupe d'opérateurs (operatorgroup) et un abonnement CR (subscription CR) :

[source,bash,role=execute]
----
cat << EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: openstack-test-operator-index
  namespace: openstack-operators
spec:
  sourceType: grpc
  secrets:
    - "osp-operators-secret"
  gprcPodConfig:
    securityContextConfig: legacy
  # adjust the repolink below to match your environment:
  image: quay.io/redhat_emp1/rh-osp-demo-ga-test-operator-index:latest
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: test-operator-openstack
  namespace: openstack-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openstack-test-operator
  namespace: openstack-operators
spec:
  name: openstack-test-operator
  channel: stable-v1.0
  source: openstack-test-operator-index
  sourceNamespace: openstack-operators
EOF
----

Lorsque le pod test-operator-controller-manager est généré avec succès et que le pod est en cours d'exécution, vous pouvez communiquer avec l'opérateur à l'aide des ressources personnalisées (CR) que l'opérateur de test accepte :
[source,bash,role=execute]
----
oc get pods -n openstack-operators
----

## Exécuter les tests Tempest

Dans le terminal bastion, assurez-vous que vous êtes dans le répertoire lab :
+
[source,bash,role=execute]
----
cd labrepo/content/files
----

Appliquez le fichier *test-v1beta1-tempest* :

[source,bash,role=execute]
----
oc apply -f test-v1beta1-tempest.yaml
----

## Accès aux modules de test

Vous pouvez accéder aux journaux Tempest, par exemple pour un test terminé avec succès ou pour dépanner un pod qui a échoué.

Obtenez le nom et le statut du pod concerné :

[source,bash,role=execute]
----
oc get pods | grep -i tempest-tests
----

Récupérez les journaux. Remplacez <pod_name> par le nom du pod que vous avez obtenu à l'étape précédente:
[source,bash,role=execute]
----
oc logs <pod_name>
----

### Récupération des journaux depuis l'intérieur du pod

Vous pouvez accéder aux journaux Tempest, par exemple, pour un test qui s'est terminé avec succès ou pour dépanner un pod qui a échoué. Vous pouvez accéder à des journaux Tempest spécifiques et plus détaillés depuis l'intérieur du pod. 
  
Get the name and status of the relevant pod:

[source,bash,role=execute]
----
oc get pods | grep -i tempest-tests
----

Accédez au pod. Remplacez <pod_name> par le nom du pod que vous avez obtenu à l'étape précédente :
[source,bash,role=execute]
----
oc debug <pod_name>
----

Afficher les fichiers journaux disponibles à l'intérieur du pod :
[source,bash,role=execute]
----
sh-5.1$ ls -lah /var/lib/tempest/external_files
----

Afficher les fichiers journaux disponibles dans le répertoire requis :

[source,bash,role=execute]
----
sh-5.1$ ls -lah /var/lib/tempest/external_files/<tempest-tests>
----

Pour plus d'informations, consultez la documentation officielle : https://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0/html-single/validating_and_troubleshooting_the_deployed_cloud/index#using-tempest-operator_diagnostics
