apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm-compute-1
spec:
  env:
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
    - name: ANSIBLE_VERBOSITY
      value: "2"
  services:
    - bootstrap
    - configure-network
    - validate-network
    - install-os
    - configure-os
    - ssh-known-hosts
    - run-os
    - reboot-os
    - install-certs
    - ovn
    - neutron-metadata
    - libvirt
    - nova
    - telemetry
  preProvisioned: true
  nodes:
      edpm-compute-1:
        hostName: edpm-compute-1.sandbox-2l8fm-ocp4-cluster.svc.cluster.local
        ansible:
          ansibleHost: 172.22.0.101
        networks:
        - name: ctlplane
          subnetName: subnet1
          defaultRoute: false
          fixedIP: 172.22.0.101
        - name: internalapi
          subnetName: subnet1
          fixedIP: 172.17.0.101
        - name: storage
          subnetName: subnet1
          fixedIP: 172.18.0.101
        - name: tenant
          subnetName: subnet1
          fixedIP: 172.19.0.101
  nodeTemplate:
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    ansible:
      ansibleUser: cloud-user
      ansibleVarsFrom:
      - prefix: subscription_manager_
        secretRef:
          name: subscription-manager
      ansibleVars:
         edpm_network_config_template: |
           ---
           {% set mtu_list = [ctlplane_mtu] %}
           {% for network in nodeset_networks %}
           {{ mtu_list.append(lookup('vars', networks_lower[network] ~ '_mtu')) }}
           {%- endfor %}
           {% set min_viable_mtu = mtu_list | max %}
           network_config:
           - type: ovs_bridge
             name: {{ neutron_physical_bridge_name }}
             mtu: {{ min_viable_mtu }}
             use_dhcp: false
             dns_servers: {{ ctlplane_dns_nameservers }}
             domain: {{ dns_search_domains }}
             addresses:
             - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_cidr }}
             routes: {{ ctlplane_host_routes }}
             members:
            - type: interface
              name: eth1
              mtu: {{ min_viable_mtu }}
              # force the MAC address of the bridge to this interface
              primary: true
            - type: interface
              name: eth2
              mtu: {{ internalapi_mtu }}
              use_dhcp: false
              addresses:
              - ip_netmask:
                  {{ internalapi_ip }}/{{ internalapi_cidr }}
              routes: {{ internalapi_host_routes }}
            - type: interface
              name: eth3
              mtu: {{ storage_mtu }}
              use_dhcp: false
              addresses:
              - ip_netmask:
                  {{ storage_ip }}/{{ storage_cidr }}
              routes: {{ storage_host_routes }}
            - type: interface
              name: eth4
              mtu: {{ tenant_mtu }}
              use_dhcp: false
              addresses:
              - ip_netmask:
                  {{ tenant_ip }}/{{ tenant_cidr }}
              routes: {{ tenant_host_routes }}     
          ---
         edpm_network_config_hide_sensitive_logs: false
          #
          # These vars are for the network config templates themselves and are
          # considered EDPM network defaults (for all computes).
         neutron_physical_bridge_name: br-osp
         edpm_ovn_bridge_mappings: datacentre:br-osp
         edpm_ovn_bridge: br-int
         edpm_ovn_encap_type: geneve
         ovn_monitor_all: true
         edpm_ovn_remote_probe_interval: 60000
         edpm_ovn_ofctrl_wait_before_clear: 8000
         ctlplane_host_routes: []
         ctlplane_subnet_cidr: 24
         dns_search_domains: sandbox-UUID-ocp4-cluster.svc.cluster.local
         ctlplane_mtu: 1500
         external_mtu: 1500
         external_cidr: '24'
         external_host_routes: []
         internalapi_mtu: 1500
         internalapi_cidr: '24'
         internalapi_host_routes: []
         storage_mtu: 1500
         storage_cidr: '24'
         storage_host_routes: []
         tenant_mtu: 1500
         tenant_cidr: '24'
         tenant_host_routes: []
         # name of the first network interface on the compute node:
         neutron_public_interface_name: eth0
         # edpm_nodes_validation
         edpm_nodes_validation_validate_controllers_icmp: false
         edpm_nodes_validation_validate_gateway_icmp: false
         gather_facts: false
         enable_debug: false
         edpm_sshd_allowed_ranges: ['172.22.0.0/16']
         edpm_podman_buildah_login: true
         edpm_container_registry_logins:
          registry.redhat.io:
            6340056|osp-on-ocp-lb1374: "eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiI1Y2EzM2NjNGY4NWM0MmZmYTI3YmU5Y2UyMWI3M2JjMCJ9.GAxgg6Ht2oCS8zxHdwQw9kSD6RHeQOWYaDOcnQB5RElewQKvZmcNWi-YJdInJ5iXTE9r9tGVIN7fhFJL7f-hhL1PK2RVzZHD8qyfkMWcCEF5GUvp8rDX4GDrSkqjpUD44teWYkOy9Nb-3pOGzRIC7qs88uSxMz7hfil4I_HmjF4AAPIi4j3QZhp0lqrXzzf7vt6NLlizDFa2XTcPf_vQqReFu3A_5iWfy8XmLlC7QIixeVv2IE-ahRqM_UDCf5Dg3n2WpYvmP5jcSPFOLoT7sMimyeaPBna793boiX2swmeGHQ23tx1nFavCUavGv_cDRAvzVXCJ2NROTJ5unHiN7CXEbzm4Rg-65tY4D0YynTU8L6t0gYtXYYY9_wi1xNs-cShAmCMh1ySJn9nBcq4ydvH7eQnhSEvoK0bPsN_vWJCgOQBQyOdpTfRMU6piAy9H1zJ0KzsSzuKSS8fX0m9oN7narZPl34DTiEUTDeW8_SS6vJjHr_Q9O_X4mVeeQhH2ocN_4M9R6A89tmQ2jObuWm-cu1Yk-G6FSPUONhsoC_99nQnICS4mAuCWWDHxFY61hIrreVZBSH053MgfSaG2sqTb26MkxKWx-TP1sx18pb1xmo4IQEwILIbLlSPA3vafbrbQO5RQcm3UYKtYwev0vAlL5taXiTuLEyPscdzv0Sc"
         edpm_bootstrap_command: |
           subscription-manager register --username "{{ subscription_manager_username }}" --password "{{ subscription_manager_password }}"
           sudo subscription-manager release --set=9.4
           sudo subscription-manager repos --disable=*
           sudo subscription-manager repos --enable=rhel-9-for-x86_64-baseos-eus-rpms --enable=rhel-9-for-x86_64-appstream-eus-rpms --enable=rhel-9-for-x86_64-highavailability-eus-rpms --enable=fast-datapath-for-rhel-9-x86_64-rpms --enable=rhoso-18.0-for-rhel-9-x86_64-rpms --enable=rhceph-7-tools-for-rhel-9-x86_64-rpms